### PR TITLE
bump to 1.3.3

### PR DESCRIPTION
**Pull request by dougalsutherland**
```
This is bugfix release, mostly focused on cleaning several detrimental corner cases scenarios.
It is nonetheless a recommended upgrade.

Changes Summary
perf: improved zstd_opt strategy (levels 16-19)
fix : bug #944 : multithreading with shared ditionary and large data, reported by @gsliepen
cli : change : -o can be combined with multiple inputs, by @terrelln
cli : fix : content size written in header by default
cli : fix : improved LZ4 format support, by @felixhandte
cli : new : hidden command -b -S, to benchmark multiple files and generate one result per file
api : change : when setting pledgedSrcSize, use ZSTD_CONTENTSIZE_UNKNOWN macro value to mean "unknown"
api : fix : support large skippable frames, by @terrelln
api : fix : re-using context could result in suboptimal block size in some corner case scenarios
api : fix : streaming interface was adding a useless 3-bytes null block to small frames
build: fix : compilation under rhel6 and centos6, reported by @pixelb
build: added check target
build: improved meson support, by @shawnl
```

### CODE REVIEW

**Comment by jakirkham** [comment]
Are all the patches still necessary? Haven't looked personally just curious to know if we can drop any yet.

Any thoughts on this @rmax?

**Comment by dougalsutherland** [comment]
I didn't really investigate, just noticed that they're all Windows things and the changelog didn't seem to say anything relevant. :)

**Comment by rmax** [comment]
@jakirkham We can check that in another PR. The two first patches are related to compilation issues in anaconda's VS environment. IIRC, the two last ones are compatibility patches (i.e.: removing optimization flags and keep the naming consistent with the other platforms).

**Comment by jakirkham** [comment]
Sure. Didn't mean it as a blocker. Was only curious if this would be a good opportunity to simplify things. :)

**Pull request merged**
