### PR TITLE
V1.4.8

### PR DESCRIPTION
**Pull request by hmaarrfk**
Closes #47 #48

Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by hmaarrfk** [comment]
@conda-forge-admin please rerender

**Comment by xhochy** [comment]
@hmaarrfk thanks, also feel free to add yourself as a maintainer in future to get faster merges (by yourself 😉)

**Comment by hmaarrfk** [comment]
why can i do that? Wouldn't i still need the maintainers to merge that request?

**Comment by xhochy** [comment]
> why can i do that? Wouldn't i still need the maintainers to merge that request?

Sure, I would merge that. Then you could continue without waiting for me 😉

**Pull request merged**
