### PR TITLE
update to 1.3.2

### PR DESCRIPTION
**Pull request by keuv-grvl**

### CODE REVIEW

**Comment by keuv-grvl** [comment]
Looks like the error come from `undefined reference to 'clock_gettime'`. 
According to https://stackoverflow.com/a/32649327, we have to explicity link to `librt` when glibc <2.17.
Shall we patch the `Makefile`, or file a issue to the zstd repo ?

**Comment by rmax** [comment]
> Shall we patch the Makefile, or file a issue to the zstd repo ?

My approach is the following:

- Check if the issue is already fixed in the repo
- Check if there is a PR that fixes the issue
- Check if there is a third-party patch (e.g.: from homebrew, apt, arch, etc)

If the problem is not reported in the project, then create an issue. If there is a patch, then backport the patch into the recipe. If there is no patch, attempt to fix the problem, create the patch and also submit a PR to the main repo.

**Comment by rmax** [comment]
@jakirkham I never asked. Does the approach I describe above fit conda-forge's general guidelines?

**Comment by jakirkham** [comment]
That's what I try to do. :) IOW SGTM. We should probably document it as guidelines though. If you want to submit a PR to the webpage repo to add that to the guidelines, that would be great. ;)

**Comment by jakirkham** [comment]
Is this good to go @rmax?

**Pull request merged**
