### PR TITLE
zstd-static for windows

### PR DESCRIPTION
**Pull request by isuruf**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by isuruf** [comment]
@conda-forge-admin, rerender

**Comment by hmaarrfk** [comment]
Can you speak about your use case for this?

**Comment by isuruf** [comment]
https://github.com/conda-forge/_libarchive_static_for_cph-feedstock/pull/25

**Comment by JohanMabille** [comment]
We also need this in the context of powerloader / micromamba. Is there any blocker that prevents from merging it?

**Comment by wolfv** [comment]
@conda-forge-admin, please rerender

**Comment by isuruf** [comment]
@wolfv, as @hmaarrfk  is a maintainer of zstd, I would have appreciated it if you gave the time to @hmaarrfk to review. There's no reason for you to merge a two month old PR without giving a heads up.

**Comment by hmaarrfk** [comment]
I presume it has to do with some micromamba needs.

**Comment by hmaarrfk** [comment]
no issues. I am somewhat interested in dealing with lingering "legacy" static packages, but I think i can deal with this later.

**Comment by wolfv** [comment]
Sorry @hmaarrfk I should've pinged you again!

**Comment by hmaarrfk** [comment]
my ask would be that more "notes" be added next to these requests. Something like:

```
# 202301 - woflv -- I plan to use the zstd-static package in XXXXXX
```

**Comment by hmaarrfk** [comment]
but no need to do anything today for zstd. just for "future" packages.

**Pull request merged**
