### PR TITLE
MNT: rerender

### PR DESCRIPTION
**Pull request by conda-forge-linter**
Hi! This is the friendly automated conda-forge-webservice.

I've rerendered the recipe as instructed in #58.

Here's a checklist to do before merging.
- [ ] Bump the build number if needed.

### CODE REVIEW

**Comment by h-vetinari** [comment]
Thanks for tackling this. I was thinking about it when I looked at #58, but I think this is currently not compatible with the way that zstd_static (as an output) depends on the shared zstd, because now the cmake files will clobber each other.

However, I don't see why those outputs _have_ to be chained together like that, so it's probably fine to remove

**Comment by h-vetinari** [comment]
I also wanted to look up the cmake invocation necessary to test this in the recipe...

**Comment by hmaarrfk** [comment]
Ultimately, you will want to split the development files.

Honestly, I'm not so sure why we would jump through these hoops for this package as a static package.

I would likely just remove it. But i haven't investigated if it is used at all

**Comment by h-vetinari** [comment]
No idea either why a static build might be needed, but I assumed it got added for a reason, so starting point would have been to keep it, but I wouldn't mind if it gets removed (assuming it's not a hard requirement somewhere).

> Ultimately, you will want to split the development files.

Not sure I understand what you mean here - could you explain?

**Pull request closed without merging**
